# Generated by Django 5.0.6 on 2024-06-10 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_driver_user_alter_passenger_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='make',
            new_name='maker',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='air_conditioned',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='vehicle_make',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='vehicle_model',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='vehicle_number',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='vehicle_type',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.vehicle'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='max_seats',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.CharField(default='Not Specified', max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='series',
            field=models.CharField(blank=True, default='Not Specified', max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='type',
            field=models.CharField(default='Not Specified', max_length=50),
        ),
    ]
