# Generated by Django 5.0.6 on 2024-06-11 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_rename_make_vehicle_maker_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerTripApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.passenger')),
                ('trip_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.triprequest')),
            ],
            options={
                'unique_together': {('trip_request', 'passenger')},
            },
        ),
    ]
